/'
WorkBreakdownStructure.puml
Template for WBS diagram.

Copyright (c) 2019 yasuaki-miyoshi

Released under the MIT license.
see http://opensource.org/licenses/mit-license.php
'/
@startwbs WorkBreakdownStructure
!include ../WbsDesign.iuml
/'
以下のような構成で記述すること
+ 最終目標
++ 1. 成果物
+++ 1.1 要素成果物(ワークパッケージ)
++++ 1.1.1 活動・作業(アクティビティ)
++++ 1.1.2 活動・作業(アクティビティ)
+++ 1.2 要素成果物(ワークパッケージ)
++++ 1.2.1 活動・作業(アクティビティ)
++++ 1.2.2 活動・作業(アクティビティ)
++ 2. 成果物
+++ 2.1 要素成果物(ワークパッケージ)
++++ 2.1.1 活動・作業(アクティビティ)
++++ 2.1.2 活動・作業(アクティビティ)
'/
+ 最終目標
++ 1. 成果物
+++ 1.1 要素成果物(ワークパッケージ)
++++ 1.1.1 活動・作業(アクティビティ)
@endwbs
