/'
WorkBreakdownStructure.puml
Template for WBS diagram.

MIT License

Copyright (c) 2019 yasuaki-miyoshi

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
'/
@startwbs WorkBreakdownStructure
/'
以下のような構成で記述すること
+ 最終目標
++ 1. 成果物
+++ 1.1 要素成果物(ワークパッケージ)
++++ 1.1.1 活動・作業(アクティビティ)
++++ 1.1.2 活動・作業(アクティビティ)
+++ 1.2 要素成果物(ワークパッケージ)
++++ 1.2.1 活動・作業(アクティビティ)
++++ 1.2.2 活動・作業(アクティビティ)
++ 2. 成果物
+++ 2.1 要素成果物(ワークパッケージ)
++++ 2.1.1 活動・作業(アクティビティ)
++++ 2.1.2 活動・作業(アクティビティ)
'/
+ 最終目標
++ 1. 成果物
+++ 1.1 要素成果物(ワークパッケージ)
++++ 1.1.1 活動・作業(アクティビティ)
@endwbs
