/'
WbsDesign.iml
This file defines the design of WBS diagram which is created by PlantUML.

Copyright (c) 2019 yasuaki-miyoshi

Released under the MIT license.
see http://opensource.org/licenses/mit-license.php
'/
skinparam shadowing false
<style>
wbsDiagram {
  ' common setting
  LineColor #A2A6B1
  node {
    ' level1. style setting of final product
    :depth(0) {
      BackgroundColor #203864
      FontColor White
    }
    ' level2. style setting deliverables
    :depth(1) {
      BackgroundColor #2F5596
      FontColor White
    }
    ' level3. style setting of work packages
    :depth(2) {
      BackgroundColor #4473C5
      FontColor White
    }
    ' level4. style setting for activities
    :depth(3) {
      BackgroundColor #DAE3F4
    }
  }
}
</style>
