name: Markdown Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check Markdown file format
    steps:
    - uses: actions/checkout@v3
    - uses: articulate/actions-markdownlint@v1
      with:
        config: .markdownlint.json
        files: 'template/**/*.md'
